name: 'jfr-static-image-action'
description: 'Build the JFR static image and run the Jenkins pipeline with Jenkinsfile-runner in this built container'
inputs:
  command:
    description: Jenkinsfile-runner command, i.e; run or lint
    default: run
    required: false
  jenkinsfile:
    description: Jenkinsfile location to test
    default: Jenkinsfile
    required: true
  pluginstxt:
    description: plugins list relative location in the repository
    default: plugins.txt
    required: false   
  jcasc:
    description: Jenkins CasC file
    required: false    
runs:
  using: "composite"
  steps:
    - uses: docker/build-push-action@v3
      with:
        context: "${{github.action_path}}"
        tags: jenskinsfile-runner-github-actions:latest
        push: false
    - uses: addnab/docker-run-action@v3
      with: 
        image: jenskinsfile-runner-github-actions:latest
        shell: bash
        options: -v ${{ github.workspace }}:/work
        run: /entrypoint.sh ${{inputs.command}} ${{inputs.jenkinsfile}} ${{inputs.pluginstxt}} ${{inputs.jcasc}}
  # using: 'docker'
  # image: 'Dockerfile'
  # pre-entrypoint: 'setup.sh'
  # args:
  #   - ${{inputs.command}}
  #   - ${{inputs.jenkinsfile}}
  #   - ${{inputs.pluginstxt}}
  #   - ${{inputs.jcasc}}