ARG BASE_IMAGE
FROM ghcr.io/jenkinsci/jenkinsfile-runner:master as cache
FROM $BASE_IMAGE
COPY --from=cache /app /app
COPY --from=cache /usr/share/jenkins/ref/plugins /usr/share/jenkins/ref/plugins
COPY --from=cache /usr/share/jenkins/ref/casc /usr/share/jenkins/ref/casc
ENV JENKINS_UC https://updates.jenkins.io
ENV CASC_JENKINS_CONFIG /usr/share/jenkins/ref/casc
ENV JDK_11 true
ADD entrypoint.sh /entrypoint.sh
RUN apk add openjdk11 bash && cd /app/jenkins && jar -cvf jenkins.war *
ADD init.groovy /app/jenkins/WEB-INF/groovy.init.d/init.groovy
ENTRYPOINT ["/entrypoint.sh"]
