name: 'jenkins-plugin-installation-action'
description: 'Install the plugins to used in the Jenkins pipeline.'
inputs:
  pluginstxt:
    description: plugins list relative location in the repository
    default: plugins.txt
    required: false
runs:
  using: "composite"
  steps:
    - name: Download plugins
      run: ${GITHUB_ACTION_PATH}/setup.sh ${{inputs.pluginstxt}}
      shell: bash
